### ISSUE TITLE
Allow specifying the toolchain binaries

### ISSUE THREAD

**Issue by ghost** [rochus-keller/BUSY#13]
For example, `CC`, `CXX`, `CPP`, `CXXCPP`,...

On LTS Linux, the toolchain shipped with your system is sometimes too old. The distribution itself or a third party repository provides packages for you to install a newer toolchain, but the newer toolchain's binaries are suffixed with the version number to allow it to coexist with the original toolchain, e.g: gcc-11, g++13,... This is by design, you can't tell me to simply rename gcc-11, g++13,... to gcc, g++,... to suite BUSY like you previously said on #12.

**Comment by rochus-keller** [comment]
Why don't you just make an alias, e.g. gcc-11-gcc, and then use gcc-11- as the prefix?

If I want to offer random names for the commands, I have to redesign the whole system including all internal APIs, and the architecture becomes ugly. 

I was thinking for a long time how to allow for custom toolchain specifications, but I don't have a good solution yet. You can have a look at how it is implemented e.g. in GN: https://gn.googlesource.com/gn/+/main/docs/reference.md#func_toolchain. This takes the complexity of everything to a higher level. It has impact on the specification language, I would have to offer some kind of reusable BUSY include files (so the toolchain doesn't have to be specified for each project) and some kind of default management with persistent state. This is just too much effort and impact to cope with some random naming variations which can easily be handled with operating system means.

**Comment by ghost** [comment]
> Why don't you just make an alias, e.g. gcc-11-gcc, and then use gcc-11- as the prefix?

Please elaborate more. I don't understand what you said. BUSY ignored the prefix and only care about the suffix to be `gcc` or not? So something like `x86_64-w64-mingw32-gcc` will be detected as only `gcc` and will work without needing any changes?

**Comment by rochus-keller** [comment]
Your gcc-11 executable is a file which lives e.g. in /usr/bin/gcc-11. Since it is a file you can make a e.g. a soft link using `sudo ln -s /usr/bin/gcc-11 /usr/bin/gcc-11-gcc`. You have to do this also for ar.

Or you can create an alias for the command, see e.g. https://linuxize.com/post/how-to-create-bash-aliases/.

**Comment by ghost** [comment]
> BUSY ignored the prefix and only care about the suffix to be `gcc` or not? So something like `x86_64-w64-mingw32-gcc` will be detected as only `gcc` and will work without needing any changes?

@rochus-keller Please confirm if this is true or not.

**Comment by rochus-keller** [comment]
> BUSY ignored the prefix and only care about the suffix to be gcc

The sentence per se makes no sense because there is no suffix; BUSY supports the GCC, CLANG and MSVC toolchains; for the GCC toolchain BUSY calls "gcc" to compile and link, and "ar" to create static libraries. If the parameter target_toolchain_prefix is set (see http://software.rochus-keller.ch/busy_spec.html#11920), "\<prefix\>gcc" or "\<prefix\>ar" is called instead. The parameter target_toolchain_prefix can be set either in the BUSY file or via BUSY command line (-P command line option, see https://github.com/rochus-keller/BUSY#running-busy).

> So something like x86_64-w64-mingw32-gcc will be detected as only gcc and will work without needing any changes?

If you have a compiler on your system with the executable name x86_64-w64-mingw32-gcc, then you have to set the target_toolchain_prefix parameter to x86_64-w64-mingw32- to use it. Also note that the path to the toolchain executable can be set using the target_toolchain_path parameter.
