### ISSUE TITLE
Could I use the system's lua?

### ISSUE THREAD

**Issue by ghost** [rochus-keller/BUSY#6]
On attempt to build LeanCreator from source on MSYS2 UCRT64 (https://github.com/rochus-keller/LeanCreator/issues/9), I tried to use the MSYS2 UCRT64's lua (installed via package `mingw-w64-ucrt-x86_64-lua`) and the command `lua build.lua ../LeanCreator` failed with:

```
$ lua build.lua ../LeanCreator
C:\msys64\clang64\bin\lua.exe: build.lua:20: module 'BUSY' not found:
        no field package.preload['BUSY']
        no file 'C:\msys64\clang64\bin\..\share\lua\5.4\BUSY.lua'
        no file 'C:\msys64\clang64\bin\..\share\lua\5.4\BUSY\init.lua'
        no file 'C:\msys64\clang64\bin\..\lib\lua\5.4\BUSY.lua'
        no file 'C:\msys64\clang64\bin\..\lib\lua\5.4\BUSY\init.lua'
        no file '.\BUSY.lua'
        no file '.\BUSY\init.lua'
        no file 'C:\msys64\clang64\bin\..\lib\lua\5.4\BUSY.dll'
        no file 'C:\msys64\clang64\bin\..\lib\lua\5.4\loadall.dll'
        no file '.\BUSY.dll'
stack traceback:
        [C]: in function 'require'
        build.lua:20: in main chunk
        [C]: in ?
```

```
$ lua -v
Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio
```

**Comment by rochus-keller** [comment]
The BUSY build system is integrated with its own Lua code base (originally Lua 5.1); taking it apart and integrating with another - possibly external - Lua version would give some work and would definitely make the bootstrap process more complicated. If you just take an arbitrary Lua it cannot find the BUSY package because there is no separate BUSY package (yet) which can be called from another Lua version.

Why do you want to use a separate Lua version? I would recommend to just use the original BUSY code base (which includes Lua 5.1).
